// Empty-chat prompt suggestions — a small, reusable capability ("API-first").
//
// Contract (this is the API the UI calls; the UI never builds suggestions itself):
//   getSuggestions({ tab, settings, signal }) -> { items: string[], source }
//   siteMetadata(tab)                          -> lightweight metadata object
//   FALLBACK_SUGGESTIONS                       -> universal, model-free ideas
//
// Design notes:
//   • BYO by default — page-specific ideas are generated by the user's *own*
//     configured model via the single `streamChat` chokepoint (so redaction and
//     runtime-context apply for free). No ChatPanel backend, no cost to us.
//   • Privacy-minimal — we send ONLY lightweight metadata (cleaned URL, title,
//     description, og:type/site, first h1, lang). Never the page body.
//   • Opt-in — gated by `settings.ui.suggestions.enabled` (default off) so simply
//     browsing never triggers a model call. Turn it on once for every site.
//   • Provider-shaped — `PROVIDERS` maps a backend name to an implementation, so
//     the same contract can later be served as a hosted value-added API
//     (api.chatpanel.net) or ported into the gateway by adding a `hosted` entry,
//     without touching callers.
// providers.js is imported at the call site, not here: this module is on the side panel's
// first paint and providers pulls 169 KB of turn machinery that no paint needs.
import { createFallbackChain } from './model-fallback.js';
import { getTarget, resolveTarget } from './store.js';

// Universal ideas that are useful on almost any page. Shown instantly, and used
// whenever smart suggestions are off, still loading, or fail.
export const FALLBACK_SUGGESTIONS = [
  'Summarize this page',
  'Explain this simply',
  'Questions I should ask about this',
  'Translate this page',
];

const CACHE_PREFIX = 'cpSugg:';
const CACHE_TTL_MS = 6 * 60 * 60 * 1000; // per-origin, so re-opening a site is free
// Must equal MAX_SUGGESTIONS in @chatpanel/events/extraction.js, which is what the prompt
// asks for and what the parser enforces. Not imported: this module is on the side panel's
// FIRST PAINT, and the structured layer it lives in is 50 KB that no panel needs to paint —
// so the schema is `await import()`ed at the two call sites below instead, and a test asserts
// the two numbers still agree.
const MAX_ITEMS = 4;

/** The schema, its prompt block and its reader — loaded only when a suggestion is generated. */
async function loadSuggestionSchema() {
  const [extraction, structured] = await Promise.all([
    import('./events/extraction.js'),
    import('./events/structured.js'),
  ]);
  return {
    schema: extraction.SUGGESTIONS_SCHEMA,
    parse: extraction.parseSuggestions,
    block: structured.describeSchema(extraction.SUGGESTIONS_SCHEMA),
  };
}

// --------------------------------------------------------------------------
// Public API
// --------------------------------------------------------------------------

// Lightweight, model-ready metadata for a tab. Reads only <head> meta + the first
// <h1> (never the page body). Falls back to title/url if the page can't be read.
export async function siteMetadata(tab) {
  const meta = { url: cleanUrl(tab?.url || ''), title: (tab?.title || '').slice(0, 200) };
  try { meta.host = new URL(tab.url).host; } catch { /* non-URL tab */ }
  Object.assign(meta, await readPageMeta(tab?.id));
  return meta;
}

// Resolve prompt suggestions for the active tab. Always resolves (never throws):
// returns the universal fallbacks unless smart suggestions are enabled AND a model
// produces usable ideas. Pass `force: true` for an explicit user action ("suggest
// for this page") — it bypasses the enabled gate AND the cache, and reports
// 'nomodel' when no model is configured so the UI can guide the user.
// `source` is 'fallback' | 'cache' | 'model' | 'nomodel'.
export async function getSuggestions({ tab, settings, signal, force = false, sourceId = null } = {}) {
  const enabled = !!settings?.ui?.suggestions?.enabled;
  if ((!enabled && !force) || !tab?.url || !/^https?:/i.test(tab.url)) {
    return { items: FALLBACK_SUGGESTIONS.slice(), source: 'fallback' };
  }
  const origin = originOf(tab.url);
  if (origin && !force) {
    const cached = await cacheGet(origin);
    if (cached) return { items: cached, source: 'cache' };
  }
  const provider = PROVIDERS[settings.ui?.suggestions?.provider] || PROVIDERS.byo;
  try {
    const meta = await siteMetadata(tab);
    const items = await provider({ meta, settings, signal, sourceId });
    if (items.length >= 2) {
      if (origin) cacheSet(origin, items); // fire-and-forget
      return { items, source: 'model' };
    }
    // Empty result with no usable model configured → tell the caller (only matters
    // for an explicit click; auto just shows fallbacks).
    if (force && !pickSuggestionAgent(settings)) {
      return { items: FALLBACK_SUGGESTIONS.slice(), source: 'nomodel' };
    }
  } catch { /* fall through to fallbacks */ }
  return { items: FALLBACK_SUGGESTIONS.slice(), source: 'fallback' };
}

// Meeting-aware variant: instead of page ideas, suggest CLARIFYING QUESTIONS to ask
// (or monitor) about a LIVE meeting, grounded in its running summary + recent
// transcript. On-demand only (the caller decides when) so it never auto-spends tokens.
// Returns { items: string[], source }. Never throws.
export async function getMeetingSuggestions({ meeting, settings, signal } = {}) {
  if (!suggestionCandidates(settings).length) return { items: [], source: 'nomodel' };
  if (!meeting || (!meeting.summary && !meeting.transcript)) return { items: [], source: 'fallback' };
  const { schema, block } = await loadSuggestionSchema();
  const sys =
    'You are assisting during a LIVE meeting. Suggest 4 short, specific CLARIFYING QUESTIONS the ' +
    'user might want answered or kept watch on as the call continues — open decisions, owners, ' +
    'risks, deadlines, unclear points. Each 3–9 words, phrased as a question, grounded ONLY in the ' +
    `summary/transcript provided (never invent).\n\n${block}`;
  const user = `Meeting: ${meeting.title || 'Meeting'}\n\nRUNNING SUMMARY:\n${meeting.summary || '(none yet)'}`
    + `\n\nRECENT TRANSCRIPT:\n${String(meeting.transcript || '').slice(-4000)}`;
  const { items } = await askForSuggestions(settings, {
    schema,
    system: sys,
    prompt: user,
    signal,
    // WHICH THREAD THIS BELONGS TO. A turn with no parent cannot be grouped. This read a bare
    // `sourceId` declared on getSuggestions — a DIFFERENT function — so it threw, the chain
    // read the throw as "candidate failed", and the feature never ran while cooling every
    // candidate it shares with page suggestions. See tools/test-suggestion-fallback.mjs.
    usage: { surface: 'suggestion', sourceId: meeting.id || null },
    max: MAX_ITEMS,
  });
  return { items, source: items.length ? 'model' : 'fallback' };
}

// --------------------------------------------------------------------------
// Providers — backend implementations behind the same contract.
// --------------------------------------------------------------------------

const PROVIDERS = {
  // Bring-your-own: generate via the user's configured model.
  byo: async ({ meta, settings, signal, sourceId = null }) => {
    if (!suggestionCandidates(settings).length) return [];
    const { schema, block } = await loadSuggestionSchema();
    const sys =
      'You suggest things a user might ask an AI assistant about the web page they are ' +
      'currently viewing. You are given ONLY lightweight page metadata — never the page ' +
      'body. Propose 4 short, specific, genuinely useful prompts (each 3–7 words, an ' +
      'imperative or a question) tailored to what this kind of page is for.\n\n' + block;
    // Threaded in, rather than read off a `meeting` that was never in scope here.
    const { items } = await askForSuggestions(settings, {
      schema,
      system: sys,
      prompt: `Page metadata:\n${JSON.stringify(meta)}`,
      signal,
      usage: { surface: 'suggestion', sourceId },
      max: MAX_ITEMS,
    });
    return items;
  },
  // 'hosted' (api.chatpanel.net / gateway) can slot in here later — same contract.
};

// Choose which configured API/agent generates the suggestions. If the user picked
// one explicitly (`targetId`), honor it — even a bridge/CLI agent. Otherwise use the
// active target, but avoid spawning a CLI just for autocomplete by falling back to a
// configured HTTP endpoint. Returns a streamChat-ready agent, or null when nothing
// usable is configured (→ fallbacks, no broken call).
/**
 * Every model that could answer, in the order worth trying — not one pick.
 *
 * A single pick meant one dead endpoint killed the feature. A user running a local model
 * that was not started got an instant connection refusal and fallback text, while a
 * perfectly good CLI agent and remote endpoint sat unused: the old picker skipped bridge
 * agents entirely and then took the FIRST endpoint with a model, reachable or not.
 *
 * Bridge agents are last rather than excluded. Spawning a CLI to write four short strings
 * is real cost and latency, so it is the answer only when nothing cheaper works — but
 * "expensive" is a reason to defer it, never a reason to have no suggestions at all.
 *
 * Pure and exported so the ordering is assertable without a network.
 */
/** Identity of a model candidate — same model at the same place is the same candidate. */
export const targetKey = (t) => `${t.kind || ''}:${t.id || ''}:${t.model || ''}:${t.baseUrl || ''}`;

export function suggestionCandidates(settings = {}) {
  const cfg = settings.ui?.suggestions || {};
  const out = [];
  const seen = new Set();
  const add = (t) => {
    if (!t) return;
    if (t.kind !== 'bridge' && !t.model) return;   // an endpoint with no model cannot answer
    const key = targetKey(t);
    if (seen.has(key)) return;
    seen.add(key);
    // Tight budget — suggestions are a few short strings.
    out.push(t.kind === 'bridge' ? { ...t, maxTokens: 160 } : { ...t, maxTokens: 160, temperature: 0.4 });
  };

  // An explicit choice leads. It can still be fallen through — an unreachable choice
  // should degrade, not silently disable the feature — but it is always tried first.
  if (cfg.targetId) add(resolveTarget(getTarget(settings, cfg.targetId), settings));

  const active = resolveTarget(getTarget(settings, settings.activeAgentId), settings);
  if (active && active.kind !== 'bridge') add(active);
  for (const ep of settings.endpoints || []) add(resolveTarget(ep, settings));
  if (active && active.kind === 'bridge') add(active);   // capable, but the costly answer

  return out;
}

/** Back-compat: callers that only ask "is anything configured at all?". */
function pickSuggestionAgent(settings) {
  return suggestionCandidates(settings)[0] || null;
}

// Shared with autocomplete: both features had independently shipped the same
// single-pick-and-give-up bug, so the behaviour lives in one place now.
const chain = createFallbackChain({ key: targetKey });

/**
 * Ask through the ONE structured-call path, over every candidate in order.
 *
 * This was a private wrapper around its own streamChat, which made suggestions the one
 * structured call that never asked a server to ENFORCE the shape: adding `response_format`
 * risked the chain reading a 400 on an unsupported body as a dead model. runStructured keeps
 * those apart itself, so the ladder and the chain compose instead of fighting.
 */
async function askForSuggestions(settings, { schema, prompt, system, signal, usage, max }) {
  const { parse } = await loadSuggestionSchema();
  const { runStructured } = await import('./structured-call.js');
  const got = await runStructured({
    candidates: suggestionCandidates(settings),
    chain,
    schema,
    prompt,
    system,
    settings,
    signal,
    usage,
    maxTokens: 400,
  });
  // The schema already coerced it; parse applies the suggestion-specific tidying (numbering
  // and quotes a model adds despite being told not to) and the cap.
  return { items: got ? parse(got.text, { max }) : [] };
}

/** Test-only: forget which candidates are cooling off. */
export function resetSuggestionHealth() { chain.reset(); }

// --------------------------------------------------------------------------
// Metadata extraction
// --------------------------------------------------------------------------

// Inject a tiny reader that pulls only <head> meta tags + the first <h1>. No body
// text leaves the page. Fails soft (chrome:// pages, PDF viewer, CSP) → {}.
async function readPageMeta(tabId) {
  if (tabId == null || !chrome?.scripting?.executeScript) return {};
  try {
    const [res] = await chrome.scripting.executeScript({
      target: { tabId },
      func: () => {
        const c = (sel) => document.querySelector(sel)?.getAttribute('content')?.trim() || '';
        const out = {};
        const desc = c('meta[name="description"]') || c('meta[property="og:description"]');
        if (desc) out.description = desc.slice(0, 300);
        const ogType = c('meta[property="og:type"]');
        if (ogType) out.ogType = ogType;
        const site = c('meta[property="og:site_name"]');
        if (site) out.siteName = site.slice(0, 80);
        const h1 = document.querySelector('h1')?.textContent?.trim();
        if (h1) out.h1 = h1.slice(0, 120);
        const lang = document.documentElement.getAttribute('lang');
        if (lang) out.lang = lang.slice(0, 12);
        return out;
      },
    });
    return (res && res.result) || {};
  } catch {
    return {};
  }
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// Drop query + hash (often carry tokens/PII and waste tokens); keep origin + path.
function cleanUrl(u) {
  try {
    const x = new URL(u);
    return x.origin + x.pathname;
  } catch {
    return u || '';
  }
}

function originOf(u) {
  try { return new URL(u).origin; } catch { return ''; }
}

// Per-origin session cache (cleared when the browser closes).
async function cacheGet(origin) {
  try {
    const k = CACHE_PREFIX + origin;
    const got = await chrome.storage.session.get(k);
    const v = got[k];
    if (v && Array.isArray(v.items) && v.items.length && Date.now() - v.ts < CACHE_TTL_MS) {
      return v.items;
    }
  } catch { /* session storage unavailable */ }
  return null;
}

async function cacheSet(origin, items) {
  try {
    await chrome.storage.session.set({ [CACHE_PREFIX + origin]: { ts: Date.now(), items } });
  } catch { /* best effort */ }
}

