// Empty-chat prompt suggestions — a small, reusable capability ("API-first").
//
// Contract (this is the API the UI calls; the UI never builds suggestions itself):
//   getSuggestions({ tab, settings, signal }) -> { items: string[], source }
//   siteMetadata(tab)                          -> lightweight metadata object
//   FALLBACK_SUGGESTIONS                       -> universal, model-free ideas
//
// Design notes:
//   • BYO by default — page-specific ideas are generated by the user's *own*
//     configured model via the single `streamChat` chokepoint (so redaction and
//     runtime-context apply for free). No ChatPanel backend, no cost to us.
//   • Privacy-minimal — we send ONLY lightweight metadata (cleaned URL, title,
//     description, og:type/site, first h1, lang). Never the page body.
//   • Opt-in — gated by `settings.ui.suggestions.enabled` (default off) so simply
//     browsing never triggers a model call. Turn it on once for every site.
//   • Provider-shaped — `PROVIDERS` maps a backend name to an implementation, so
//     the same contract can later be served as a hosted value-added API
//     (api.chatpanel.net) or ported into the gateway by adding a `hosted` entry,
//     without touching callers.
import { streamChat } from './providers.js';
import { getTarget, resolveTarget } from './store.js';

// Universal ideas that are useful on almost any page. Shown instantly, and used
// whenever smart suggestions are off, still loading, or fail.
export const FALLBACK_SUGGESTIONS = [
  'Summarize this page',
  'Explain this simply',
  'Questions I should ask about this',
  'Translate this page',
];

const CACHE_PREFIX = 'cpSugg:';
const CACHE_TTL_MS = 6 * 60 * 60 * 1000; // per-origin, so re-opening a site is free
const MAX_ITEMS = 4;

// --------------------------------------------------------------------------
// Public API
// --------------------------------------------------------------------------

// Lightweight, model-ready metadata for a tab. Reads only <head> meta + the first
// <h1> (never the page body). Falls back to title/url if the page can't be read.
export async function siteMetadata(tab) {
  const meta = { url: cleanUrl(tab?.url || ''), title: (tab?.title || '').slice(0, 200) };
  try { meta.host = new URL(tab.url).host; } catch { /* non-URL tab */ }
  Object.assign(meta, await readPageMeta(tab?.id));
  return meta;
}

// Resolve prompt suggestions for the active tab. Always resolves (never throws):
// returns the universal fallbacks unless smart suggestions are enabled AND a model
// produces usable ideas. Pass `force: true` for an explicit user action ("suggest
// for this page") — it bypasses the enabled gate AND the cache, and reports
// 'nomodel' when no model is configured so the UI can guide the user.
// `source` is 'fallback' | 'cache' | 'model' | 'nomodel'.
export async function getSuggestions({ tab, settings, signal, force = false } = {}) {
  const enabled = !!settings?.ui?.suggestions?.enabled;
  if ((!enabled && !force) || !tab?.url || !/^https?:/i.test(tab.url)) {
    return { items: FALLBACK_SUGGESTIONS.slice(), source: 'fallback' };
  }
  const origin = originOf(tab.url);
  if (origin && !force) {
    const cached = await cacheGet(origin);
    if (cached) return { items: cached, source: 'cache' };
  }
  const provider = PROVIDERS[settings.ui?.suggestions?.provider] || PROVIDERS.byo;
  try {
    const meta = await siteMetadata(tab);
    const items = await provider({ meta, settings, signal });
    if (items.length >= 2) {
      if (origin) cacheSet(origin, items); // fire-and-forget
      return { items, source: 'model' };
    }
    // Empty result with no usable model configured → tell the caller (only matters
    // for an explicit click; auto just shows fallbacks).
    if (force && !pickSuggestionAgent(settings)) {
      return { items: FALLBACK_SUGGESTIONS.slice(), source: 'nomodel' };
    }
  } catch { /* fall through to fallbacks */ }
  return { items: FALLBACK_SUGGESTIONS.slice(), source: 'fallback' };
}

// --------------------------------------------------------------------------
// Providers — backend implementations behind the same contract.
// --------------------------------------------------------------------------

const PROVIDERS = {
  // Bring-your-own: generate via the user's configured model.
  byo: async ({ meta, settings, signal }) => {
    const agent = pickSuggestionAgent(settings);
    if (!agent) return [];
    const sys =
      'You suggest things a user might ask an AI assistant about the web page they are ' +
      'currently viewing. You are given ONLY lightweight page metadata — never the page ' +
      'body. Propose 4 short, specific, genuinely useful prompts (each 3–7 words, an ' +
      'imperative or a question) tailored to what this kind of page is for. ' +
      'Respond with ONLY a JSON array of 4 strings, nothing else.';
    const user = `Page metadata:\n${JSON.stringify(meta)}\n\nReturn a JSON array of 4 prompt strings.`;
    let out = '';
    await streamChat({
      agent: { ...agent, systemPrompt: sys },
      settings,
      signal,
      messages: [{ role: 'user', content: user }],
      onDelta: (d) => (out += d),
    });
    return parsePrompts(out);
  },
  // 'hosted' (api.chatpanel.net / gateway) can slot in here later — same contract.
};

// Choose which configured API/agent generates the suggestions. If the user picked
// one explicitly (`targetId`), honor it — even a bridge/CLI agent. Otherwise use the
// active target, but avoid spawning a CLI just for autocomplete by falling back to a
// configured HTTP endpoint. Returns a streamChat-ready agent, or null when nothing
// usable is configured (→ fallbacks, no broken call).
function pickSuggestionAgent(settings) {
  const cfg = settings.ui?.suggestions || {};
  if (cfg.targetId) {
    const chosen = resolveTarget(getTarget(settings, cfg.targetId), settings);
    if (!chosen) return null;
    if (chosen.kind === 'bridge') return { ...chosen, maxTokens: 160 };
    return chosen.model ? { ...chosen, maxTokens: 160, temperature: 0.4 } : null;
  }
  let agent = resolveTarget(getTarget(settings, settings.activeAgentId), settings);
  if (!agent || agent.kind === 'bridge') {
    const ep = (settings.endpoints || []).find((e) => e.model) || null;
    agent = ep ? resolveTarget(ep, settings) : null;
  }
  if (!agent || !agent.model) return null;
  // Tight budget — suggestions are a few short strings.
  return { ...agent, maxTokens: 160, temperature: 0.4 };
}

// --------------------------------------------------------------------------
// Metadata extraction
// --------------------------------------------------------------------------

// Inject a tiny reader that pulls only <head> meta tags + the first <h1>. No body
// text leaves the page. Fails soft (chrome:// pages, PDF viewer, CSP) → {}.
async function readPageMeta(tabId) {
  if (tabId == null || !chrome?.scripting?.executeScript) return {};
  try {
    const [res] = await chrome.scripting.executeScript({
      target: { tabId },
      func: () => {
        const c = (sel) => document.querySelector(sel)?.getAttribute('content')?.trim() || '';
        const out = {};
        const desc = c('meta[name="description"]') || c('meta[property="og:description"]');
        if (desc) out.description = desc.slice(0, 300);
        const ogType = c('meta[property="og:type"]');
        if (ogType) out.ogType = ogType;
        const site = c('meta[property="og:site_name"]');
        if (site) out.siteName = site.slice(0, 80);
        const h1 = document.querySelector('h1')?.textContent?.trim();
        if (h1) out.h1 = h1.slice(0, 120);
        const lang = document.documentElement.getAttribute('lang');
        if (lang) out.lang = lang.slice(0, 12);
        return out;
      },
    });
    return (res && res.result) || {};
  } catch {
    return {};
  }
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// Drop query + hash (often carry tokens/PII and waste tokens); keep origin + path.
function cleanUrl(u) {
  try {
    const x = new URL(u);
    return x.origin + x.pathname;
  } catch {
    return u || '';
  }
}

function originOf(u) {
  try { return new URL(u).origin; } catch { return ''; }
}

// Extract up to MAX_ITEMS clean prompt strings from a model reply. Prefers a JSON
// array; falls back to splitting lines and stripping bullets/numbering/quotes.
function parsePrompts(text) {
  if (!text) return [];
  let arr = null;
  const m = text.match(/\[[\s\S]*\]/);
  if (m) { try { arr = JSON.parse(m[0]); } catch { /* not JSON */ } }
  if (!Array.isArray(arr)) {
    arr = text
      .split('\n')
      .map((s) => s.replace(/^[\s\-*\d.)"']+/, '').replace(/["']+\s*$/, '').trim())
      .filter(Boolean);
  }
  const seen = new Set();
  const out = [];
  for (let s of arr) {
    if (typeof s !== 'string') continue;
    s = s.trim().replace(/^["']|["']$/g, '').slice(0, 80).trim();
    const key = s.toLowerCase();
    if (!s || seen.has(key)) continue;
    seen.add(key);
    out.push(s);
    if (out.length >= MAX_ITEMS) break;
  }
  return out;
}

// Per-origin session cache (cleared when the browser closes).
async function cacheGet(origin) {
  try {
    const k = CACHE_PREFIX + origin;
    const got = await chrome.storage.session.get(k);
    const v = got[k];
    if (v && Array.isArray(v.items) && v.items.length && Date.now() - v.ts < CACHE_TTL_MS) {
      return v.items;
    }
  } catch { /* session storage unavailable */ }
  return null;
}

async function cacheSet(origin, items) {
  try {
    await chrome.storage.session.set({ [CACHE_PREFIX + origin]: { ts: Date.now(), items } });
  } catch { /* best effort */ }
}
