#!/usr/bin/env node
// Vendor pdf.js (Apache-2.0) into extension/js/vendor/.
//
// WHY VENDORED. The extension ships no bundler and CI does no install, so every third-party
// runtime dependency is a committed file. This is the same arrangement as the CodeMirror
// bundle (tools/build-editor.mjs) — rerun this after bumping pdfjs-dist, and commit what it
// writes.
//
// WHY A COPY AND NOT A BUNDLE. pdfjs-dist already publishes self-contained, minified ESM for
// both halves (the API and its worker). Re-bundling them would only add a chance to break
// something; the job here is to copy exactly two files, prove they are CSP-safe, and record
// which version they came from.
//
// WHICH BUILD, AND WHY THE LARGER ONE. `legacy/`, which costs ~120 KB more than the modern
// build. The modern build refuses to run outside a browser — it needs a DOM at import time —
// so nothing in tools/ could ever exercise the file we actually ship, and a vendored engine
// that no test can load is a 1.7 MB leap of faith on every version bump. The legacy build
// runs in Node, so tools/test-pdf-reading.mjs opens a real PDF with the EXACT committed
// bytes, with no install (CI does none). It is also what keeps older Firefox ESR working.
//
// WHAT IS DELIBERATELY LEFT OUT. `cmaps/` (1.6 MB) and `standard_fonts/` (816 KB) are for
// rendering and for CJK PDFs that reference a PREDEFINED CMap rather than embedding a
// ToUnicode map. We extract text and never render, and most modern PDFs — CJK included —
// embed their own map. If a CJK document is ever reported as extracting to nothing, the fix
// is to copy `cmaps/` here and set `cMapUrl`/`cMapPacked` in js/pdf-text.js; the option is
// already threaded through. `wasm/` is image-codec territory, which text extraction never
// enters.

import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkgDir = join(root, 'node_modules', 'pdfjs-dist');
const outDir = join(root, 'extension', 'js', 'vendor');

if (!existsSync(join(pkgDir, 'legacy', 'build', 'pdf.min.mjs'))) {
  console.error('✕ pdfjs-dist is not installed. Run: npm install --no-save pdfjs-dist');
  process.exit(1);
}
const version = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).version;

// AMO refuses to PARSE a non-binary file over 5 MB, which blocks the submission outright.
// tools/build-firefox.mjs checks the staged package; catching it here names the cause.
const AMO_MAX_PARSE_BYTES = 5 * 1024 * 1024;

const FILES = [
  { from: 'legacy/build/pdf.min.mjs', to: 'pdf.js' },
  { from: 'legacy/build/pdf.worker.min.mjs', to: 'pdf.worker.js' },
];

mkdirSync(outDir, { recursive: true });
for (const { from, to } of FILES) {
  const src = join(pkgDir, from);
  const dest = join(outDir, to);
  copyFileSync(src, dest);
  const text = readFileSync(dest, 'utf8');

  // CSP guard: MV3 forbids eval and new Function outright. pdf.js is written to run under a
  // strict CSP, but a version bump is exactly when that could stop being true — and it would
  // fail at runtime, on a user's machine, inside a worker, where nobody would see it.
  // `new Function(` needs the paren: the worker defines `new FunctionBasedShading(…)`.
  const forbidden = [/\beval\s*\(/, /new\s+Function\s*\(/].find((re) => re.test(text));
  if (forbidden) {
    console.error(`✕ ${to} contains a CSP-forbidden construct (${forbidden}) — not MV3-safe`);
    process.exit(1);
  }
  const { size } = statSync(dest);
  if (size > AMO_MAX_PARSE_BYTES) {
    console.error(`✕ ${to} is ${(size / 1024 / 1024).toFixed(1)} MB — over AMO's 5 MB parse ceiling`);
    process.exit(1);
  }
  // The banner goes on AFTER the checks so the checks see only library code.
  writeFileSync(dest, `/* Vendored pdf.js ${version} (Apache-2.0) — generated by tools/build-pdf.mjs from pdfjs-dist/${from}. Do NOT edit by hand; run \`npm run build:pdf\`. */\n${text}`);
  console.log(`✓ ${to} — ${(statSync(dest).size / 1024).toFixed(0)} KB, CSP-safe`);
}

// The version is committed too, so `npm run build:pdf -- --check` can tell whether the
// vendored copy still matches the installed package without diffing a megabyte of minified
// source, and so a reader can see what they are running without opening it.
writeFileSync(join(outDir, 'pdf.version.json'), `${JSON.stringify({ name: 'pdfjs-dist', version, license: 'Apache-2.0' }, null, 2)}\n`);
console.log(`✓ vendored pdf.js ${version}`);
