// Build the vendored CodeMirror 6 bundle for the Notes live-preview editor.
//
// The extension ships NO bundler and imports raw ES modules at runtime — so CM6 (which is
// many inter-dependent @codemirror/* + @lezer/* packages) is bundled ONCE here into a
// single self-contained, CSP-safe ESM file that gets committed. That committed file is the
// source of truth (CI does not install/build); rerun `npm run build:editor` after changing
// tools/editor/entry.js or bumping the CM6 devDependencies.
//
// CSP note: Chrome MV3 forbids eval/new Function. CM6 does not use them; the build below
// asserts that so a future dependency bump can't silently break the extension's CSP.

import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outfile = join(root, 'extension', 'js', 'vendor', 'codemirror.js');

await build({
  entryPoints: [join(root, 'tools', 'editor', 'entry.js')],
  outfile,
  bundle: true,
  format: 'esm',
  minify: true,
  target: 'es2020',
  legalComments: 'none',
  banner: { js: '/* Vendored CodeMirror 6 — generated by tools/build-editor.mjs from @codemirror/* + @lezer/highlight. Do NOT edit by hand; run `npm run build:editor`. */' },
});

// CSP guard: MV3 rejects eval/new Function. Fail the build loud if the bundle contains them.
const src = readFileSync(outfile, 'utf8');
const bad = [/\beval\s*\(/, /new\s+Function\s*\(/].find((re) => re.test(src));
if (bad) {
  console.error(`✕ vendored CM6 bundle contains a CSP-forbidden construct (${bad}) — not MV3-safe`);
  process.exit(1);
}
console.log(`✓ built ${outfile} (${(src.length / 1024).toFixed(0)} KB), CSP-safe`);
